# ============================================
# PromoCode Plugin Configuration
# ============================================

# Настройки плагина
settings:
  # Префикс плагина в сообщениях
  prefix: "&x&F&C&2&2&2&2▶"
  
  # Включить отладочные сообщения
  debug: false
  
  # Проверять обновления при запуске
  check-updates: true

# Промокоды
promocodes:
  nezxenka:
    player_uses: 1
    global_uses: -1
    group: free
    needLink: false
    messages:
      - ""
      - " &6Вы получили:"
      - ""
      - " &7-&e Неженка топ"
      - ""
      - " &f* &7Промокод активируется навсегда, если ранее не выдавался"
    commands:
      - "nezxenka top"